language: python
python:
  - "3.8-dev"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
branches:
  only:
    - develop
install:
  - "pip install coveralls"
  - "pip install ."
script:
  - "cd test"
  - "coverage run --source=pybtex_docutils `type -p nosetests`"
after_success:
  - "coveralls"
