language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
branches:
  only:
    - develop
install:
  - "pip install . --use-mirrors"
before_script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then 2to3 -w -n test; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -w -n test; fi"
script:
  - "cd test"
  - "nosetests"
