language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
branches:
  only:
    - develop
install:
  - "pip install coveralls"
  - "pip install ."
script:
  - "cd test"
  - "coverage run --source=pybtex_docutils `type -p nosetests`"
after_success:
  - "coveralls"
